voyager-api:
  protocol: http
  host: ${VOYAGER_HOST}
  port: ${VOYAGER_API_PORT}
  authToken: ${VOYAGER_API_KEY}
server:
  port: ${VOYAGER_UI_PORT}
  address: 0.0.0.0
  error:
    include-message: always
spring:
  profiles:
    active: local
  logging:
    level:
      org:
        springframework:
          cache: trace