voyager-api:
  protocol: http
  host: localhost
  port: 3000
  lookupPath: /search
  townPath: /towns
  authToken: ${VOYAGER_API_KEY}
  iataPath: /iata
  nearbyAirportsPath: /nearby-airports

spring:
  profiles:
    active: local
  logging:
    level:
      org:
        springframework:
          cache: trace