voyager-api:
  protocol: http
  host: localhost
  port: 3000
  authToken: ${VOYAGER_API_KEY}

spring:
  profiles:
    active: local
  logging:
    level:
      org:
        springframework:
          cache: trace