voyager-api:
  protocol: http
  host: ${VOYAGER_HOST}
  port: 3000
  authToken: ${VOYAGER_API_KEY}
server:
  port: 8080
  error:
    include-message: always
spring:
  profiles:
    active: local
  logging:
    level:
      org:
        springframework:
          cache: trace